export const DISEASE_CATEGORIES = [
  "Common Illness",
  "Diabetes & Endocrine",
  "Heart & BP",
  "Gastro & Digestive",
  "Liver & Kidney",
  "Deficiency Diseases",
  "Respiratory",
  "Skin",
  "Mental Health",
  "Bone & Joint",
  "Women Health",
  "Others"
];

export const MASTER_DISEASES = [
  // Common Illness
  { name: "Fever", category: "Common Illness" },
  { name: "Cold", category: "Common Illness" },
  { name: "Flu", category: "Common Illness" },
  { name: "Cough", category: "Common Illness" },
  { name: "Sore throat", category: "Common Illness" },
  { name: "Allergy", category: "Common Illness" },
  { name: "Headache", category: "Common Illness" },
  { name: "Migraine", category: "Common Illness" },
  { name: "Sinusitis", category: "Common Illness" },
  { name: "Common Cold", category: "Common Illness" },
  { name: "Influenza", category: "Common Illness" },
  { name: "Viral Infection", category: "Common Illness" },
  { name: "Bacterial Infection", category: "Common Illness" },
  { name: "Ear Infection", category: "Common Illness" },
  { name: "Pink Eye (Conjunctivitis)", category: "Common Illness" },
  
  // Diabetes & Endocrine
  { name: "Diabetes Type 1", category: "Diabetes & Endocrine" },
  { name: "Diabetes Type 2", category: "Diabetes & Endocrine" },
  { name: "Prediabetes", category: "Diabetes & Endocrine" },
  { name: "Hypothyroidism", category: "Diabetes & Endocrine" },
  { name: "Hyperthyroidism", category: "Diabetes & Endocrine" },
  { name: "PCOS", category: "Diabetes & Endocrine" },
  { name: "Gestational Diabetes", category: "Diabetes & Endocrine" },
  { name: "Addison's Disease", category: "Diabetes & Endocrine" },
  { name: "Cushing's Syndrome", category: "Diabetes & Endocrine" },
  { name: "Goiter", category: "Diabetes & Endocrine" },
  { name: "Hashimoto's Thyroiditis", category: "Diabetes & Endocrine" },
  { name: "Graves' Disease", category: "Diabetes & Endocrine" },
  { name: "Metabolic Syndrome", category: "Diabetes & Endocrine" },
  { name: "Hormonal Imbalance", category: "Diabetes & Endocrine" },
  
  // Heart & BP
  { name: "Hypertension", category: "Heart & BP" },
  { name: "Hypotension", category: "Heart & BP" },
  { name: "High Cholesterol", category: "Heart & BP" },
  { name: "Heart disease", category: "Heart & BP" },
  { name: "Coronary Artery Disease", category: "Heart & BP" },
  { name: "Heart Failure", category: "Heart & BP" },
  { name: "Arrhythmia", category: "Heart & BP" },
  { name: "Angina", category: "Heart & BP" },
  { name: "Atherosclerosis", category: "Heart & BP" },
  { name: "Peripheral Artery Disease", category: "Heart & BP" },
  { name: "Stroke History", category: "Heart & BP" },
  { name: "Varicose Veins", category: "Heart & BP" },
  { name: "Deep Vein Thrombosis", category: "Heart & BP" },
  
  // Gastro & Digestive
  { name: "Acidity", category: "Gastro & Digestive" },
  { name: "GERD", category: "Gastro & Digestive" },
  { name: "Gastritis", category: "Gastro & Digestive" },
  { name: "Ulcer", category: "Gastro & Digestive" },
  { name: "Constipation", category: "Gastro & Digestive" },
  { name: "Diarrhea", category: "Gastro & Digestive" },
  { name: "IBS", category: "Gastro & Digestive" },
  { name: "IBD (Crohn's/Colitis)", category: "Gastro & Digestive" },
  { name: "Celiac Disease", category: "Gastro & Digestive" },
  { name: "Lactose Intolerance", category: "Gastro & Digestive" },
  { name: "Gallstones", category: "Gastro & Digestive" },
  { name: "Hemorrhoids", category: "Gastro & Digestive" },
  { name: "Bloating", category: "Gastro & Digestive" },
  { name: "Food Poisoning", category: "Gastro & Digestive" },
  { name: "Appendicitis History", category: "Gastro & Digestive" },
  { name: "Pancreatitis", category: "Gastro & Digestive" },
  
  // Liver & Kidney
  { name: "Fatty liver", category: "Liver & Kidney" },
  { name: "Hepatitis", category: "Liver & Kidney" },
  { name: "Kidney stone", category: "Liver & Kidney" },
  { name: "UTI", category: "Liver & Kidney" },
  { name: "CKD (Chronic Kidney Disease)", category: "Liver & Kidney" },
  { name: "Liver Cirrhosis", category: "Liver & Kidney" },
  { name: "Jaundice", category: "Liver & Kidney" },
  { name: "Kidney Failure", category: "Liver & Kidney" },
  { name: "Nephrotic Syndrome", category: "Liver & Kidney" },
  { name: "Polycystic Kidney Disease", category: "Liver & Kidney" },
  
  // Deficiency Diseases
  { name: "Anemia", category: "Deficiency Diseases" },
  { name: "Vitamin D deficiency", category: "Deficiency Diseases" },
  { name: "Vitamin B12 deficiency", category: "Deficiency Diseases" },
  { name: "Calcium deficiency", category: "Deficiency Diseases" },
  { name: "Iron deficiency", category: "Deficiency Diseases" },
  { name: "Protein deficiency", category: "Deficiency Diseases" },
  { name: "Scurvy", category: "Deficiency Diseases" },
  { name: "Rickets", category: "Deficiency Diseases" },
  { name: "Iodine deficiency", category: "Deficiency Diseases" },
  { name: "Magnesium deficiency", category: "Deficiency Diseases" },
  
  // Respiratory
  { name: "Asthma", category: "Respiratory" },
  { name: "Bronchitis", category: "Respiratory" },
  { name: "Pneumonia", category: "Respiratory" },
  { name: "COPD", category: "Respiratory" },
  { name: "Tuberculosis", category: "Respiratory" },
  { name: "Sleep Apnea", category: "Respiratory" },
  { name: "Cystic Fibrosis", category: "Respiratory" },
  { name: "Emphysema", category: "Respiratory" },
  { name: "Pulmonary Fibrosis", category: "Respiratory" },
  
  // Skin
  { name: "Acne", category: "Skin" },
  { name: "Eczema", category: "Skin" },
  { name: "Psoriasis", category: "Skin" },
  { name: "Fungal infection", category: "Skin" },
  { name: "Dermatitis", category: "Skin" },
  { name: "Rosacea", category: "Skin" },
  { name: "Vitiligo", category: "Skin" },
  { name: "Hives", category: "Skin" },
  { name: "Sunburn", category: "Skin" },
  { name: "Warts", category: "Skin" },
  { name: "Melasma", category: "Skin" },
  
  // Mental Health
  { name: "Stress", category: "Mental Health" },
  { name: "Anxiety", category: "Mental Health" },
  { name: "Depression", category: "Mental Health" },
  { name: "Insomnia", category: "Mental Health" },
  { name: "Bipolar Disorder", category: "Mental Health" },
  { name: "OCD", category: "Mental Health" },
  { name: "PTSD", category: "Mental Health" },
  { name: "ADHD", category: "Mental Health" },
  { name: "Eating Disorder", category: "Mental Health" },
  { name: "Panic Attacks", category: "Mental Health" },
  
  // Bone & Joint
  { name: "Arthritis", category: "Bone & Joint" },
  { name: "Osteoporosis", category: "Bone & Joint" },
  { name: "Back pain", category: "Bone & Joint" },
  { name: "Rheumatoid Arthritis", category: "Bone & Joint" },
  { name: "Gout", category: "Bone & Joint" },
  { name: "Spondylitis", category: "Bone & Joint" },
  { name: "Sciatica", category: "Bone & Joint" },
  { name: "Fracture Recovery", category: "Bone & Joint" },
  { name: "Osteoarthritis", category: "Bone & Joint" },
  { name: "Fibromyalgia", category: "Bone & Joint" },
  
  // Women Health
  { name: "Menstrual pain", category: "Women Health" },
  { name: "Pregnancy care", category: "Women Health" },
  { name: "Lactation care", category: "Women Health" },
  { name: "Menopause", category: "Women Health" },
  { name: "Endometriosis", category: "Women Health" },
  { name: "Fibroids", category: "Women Health" },
  { name: "Morning Sickness", category: "Women Health" },
  { name: "Postpartum Care", category: "Women Health" },
  
  // Others
  { name: "Obesity", category: "Others" },
  { name: "Underweight", category: "Others" },
  { name: "Chronic Fatigue", category: "Others" },
  { name: "Autoimmune Disease", category: "Others" },
  { name: "Cancer Recovery", category: "Others" },
  { name: "Post-Surgery Recovery", category: "Others" },
  { name: "Dengue", category: "Others" },
  { name: "Malaria", category: "Others" },
  { name: "Typhoid", category: "Others" },
  { name: "Chikungunya", category: "Others" },
  { name: "Zika Virus", category: "Others" },
  { name: "Food Allergy", category: "Others" },
  { name: "Dust Allergy", category: "Others" },
  { name: "Pollen Allergy", category: "Others" },
  { name: "Gluten Sensitivity", category: "Others" },
  { name: "High Uric Acid", category: "Others" },
  { name: "Low Immunity", category: "Others" },
  { name: "Hair Loss", category: "Others" },
  { name: "Eye Strain", category: "Others" },
  { name: "Dental Issues", category: "Others" },
  { name: "Sleep Apnea", category: "Others" },
  { name: "Restless Leg Syndrome", category: "Others" },
  { name: "Vertigo", category: "Others" },
  { name: "Tinnitus", category: "Others" },
  { name: "Motion Sickness", category: "Others" },
  { name: "Heat Stroke", category: "Others" },
  { name: "Dehydration", category: "Others" },
  { name: "Sunstroke", category: "Others" },
  { name: "Frostbite", category: "Others" },
  { name: "Altitude Sickness", category: "Others" },
  { name: "Jet Lag", category: "Others" },
  { name: "Hangover", category: "Others" },
  { name: "Burnout", category: "Others" },
  { name: "Vitamin A deficiency", category: "Others" },
  { name: "Vitamin C deficiency", category: "Others" },
  { name: "Vitamin E deficiency", category: "Others" },
  { name: "Vitamin K deficiency", category: "Others" },
  { name: "Zinc deficiency", category: "Others" },
  { name: "Potassium deficiency", category: "Others" },
  { name: "Sodium deficiency", category: "Others" }
].map((d, i) => ({ ...d, id: `disease-${i}` }));
