// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pharmacare-minimal/Minimal.tsx": () => import("../components/mockups/pharmacare-minimal/Minimal.tsx"),
  "./components/mockups/pharmacare-modern/Modern.tsx": () => import("../components/mockups/pharmacare-modern/Modern.tsx")
};
